cluster_name: pyton-ray-sandbox

provider:
  type: local
  head_ip: raynode1
  worker_ips: [raynode2]

auth:
  ssh_user: vagrant
  ssh_private_key: ~/.vagrant.d/insecure_private_key

min_workers: 2
max_workers: 2
upscaling_speed: 1.0
idle_timeout_minutes: 5

file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}
cluster_synced_files: []
file_mounts_sync_continuously: False

rsync_exclude:
  - "**/.git"
  - "**/.git/**"

rsync_filter:
  - ".gitignore"

initialization_commands: []
setup_commands:
  - if [ $(which ray) ]; then sudo pip3 uninstall ray -y; fi
  - sudo pip3 install -U ray[all]==1.6.0

head_setup_commands: []
worker_setup_commands: []

head_start_ray_commands:
  - sudo ray stop
  - sudo ulimit -c unlimited && sudo ray start --head --port=6379 --dashboard-host "0.0.0.0" --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
  - sudo ray stop
  - sudo ray start --address=$RAY_HEAD_IP:6379
