cluster_name: python-ray-minimal-manual

provider:
  type: local
  head_ip: 172.19.237.22
  worker_ips: [172.19.237.22, 172.19.239.209]

auth:
  ssh_user: vagrant
  ssh_private_key: ~/.vagrant.d/insecure_private_key
