# -*- mode: ruby -*-
# vi: set ft=ruby :

# Variables
BOX_IMAGE   = "generic/centos8"
NODE_COUNT  = 2
NODE_CPU    = 2
NODE_RAM    = 2048

Vagrant.configure(2) do |config|
    (1..NODE_COUNT).each do |i|
        config.vm.define "raynode#{i}" do |node|
            node.vm.box     = BOX_IMAGE

            # node.vm.provider "virtualbox" do |v|
            #     v.name      = "raynode#{i}"
            #     v.cpus      = NODE_CPU
            #     v.memory    = NODE_RAM
            #     v.gui       = false
            # end

            node.vm.provider "hyperv" do |h|
                h.vmname    = "raynode#{i}"
                h.cpus      = NODE_CPU
                h.maxmemory = NODE_RAM
                h.memory    = NODE_RAM
            end

            # Network
            node.vm.hostname = "raynode#{i}"
            node.vm.network "private_network", type: "dhcp"
            # node.vm.network "private_network", ip: "172.18.128.{10 + i}"
            # config.vm.network "forwarded_port", guest: 80, host: 8080

            # Setup
            node.vm.provision "shell", inline: <<-SHELL
                echo Provisioning raynode#{i}
                set -e
                hostnamectl set-hostname raynode#{i}
                localectl set-locale LANG=en_US.UTF-8
                dnf -y update
                dnf -y install epel-release
                dnf -y install dnf-plugins-core
                # dnf config-manager --set-enabled PowerTools
                dnf -y update

                dnf -y groupinstall 'Development Tools'
                dnf -y install libcurl-devel
                dnf -y install openssl-devel
                dnf -y install python3
                dnf -y install wget

                # systemctl stop firewalld
                # systemctl disable firewalld
                # systemctl mask --now firewalld

                alternatives --set python /usr/bin/python3
                alternatives --auto python
            SHELL

            # Mounts
            # config.vm.synced_folder "../data", "/vagrant_data"
        end
    end
end
