# -*- mode: ruby -*-
# vi: set ft=ruby :

# Variables
BOX_IMAGE   = "generic/centos8"
NODE_COUNT  = 2
NODE_CPU    = 2
NODE_RAM    = 2048

Vagrant.configure(2) do |config|
    # Disable SSH key generation.
    config.ssh.insert_key = false
    (1..NODE_COUNT).each do |i|
        config.vm.define "raynode#{i}" do |node|
            node.vm.box     = BOX_IMAGE

            # node.vm.provider "virtualbox" do |v|
            #     v.name      = "raynode#{i}"
            #     v.cpus      = NODE_CPU
            #     v.memory    = NODE_RAM
            #     v.gui       = false
            # end

            node.vm.provider "hyperv" do |h|
                h.vmname    = "raynode#{i}"
                h.cpus      = NODE_CPU
                h.maxmemory = NODE_RAM
                h.memory    = NODE_RAM
            end

            # Network
            node.vm.hostname = "raynode#{i}"
            node.vm.network "private_network", type: "dhcp"
            # node.vm.network "private_network", ip: "172.18.128.{10 + i}"
            # config.vm.network "forwarded_port", guest: 80, host: 8080

            # Upload insecure keys
            node.vm.provision "file", source: "#{Dir.home}/.vagrant.d/insecure_private_key", destination: "/tmp/id_rsa"
            ssh_insecure_key_pub = 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key'

            node.vm.provision "shell", inline: <<-SHELL
                echo Provisioning SSH keys and Config on raynode#{i}
                mv /tmp/id_rsa /home/vagrant/.ssh/id_rsa
                echo #{ssh_insecure_key_pub} >> /home/vagrant/.ssh/id_rsa.pub
                echo #{ssh_insecure_key_pub} >> /home/vagrant/.ssh/authorized_keys
                chmod 400 /home/vagrant/.ssh/id_rsa
                chmod 400 /home/vagrant/.ssh/id_rsa.pub
                chmod -R 600 /home/vagrant/.ssh/authorized_keys
                echo 'Host *' >> /home/vagrant/.ssh/config
                echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
                echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
                chmod -R 600 /home/vagrant/.ssh/config
                chown -R vagrant /home/vagrant/.ssh
            SHELL

            # Setup
            node.vm.provision "shell", inline: <<-SHELL
                echo Provisioning Base Software on raynode#{i}
                set -e
                hostnamectl set-hostname raynode#{i}
                localectl set-locale LANG=en_US.UTF-8
                dnf -y update
                dnf -y install epel-release
                dnf -y install dnf-plugins-core
                # dnf config-manager --set-enabled PowerTools
                dnf -y update
                dnf -y groupinstall 'Development Tools'
                dnf -y install bzip2-devel
                dnf -y install htop
                dnf -y install libcurl-devel
                dnf -y install libffi-devel
                dnf -y install openssl-devel
                dnf -y install wget
                dnf -y install xz-devel
                # systemctl stop firewalld
                # systemctl disable firewalld
                # systemctl mask --now firewalld
                cd /tmp
                wget https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz
                tar xvf Python-3.8.5.tgz
                cd Python-3.8*/
                ./configure --prefix=/usr --enable-optimizations
                sudo make altinstall
                ln -fs /usr/bin/2to3-3.8 2to3
                ln -fs /usr/bin/easy_install-3.8 easy_install
                ln -fs /usr/bin/idle3.8 idle
                ln -fs /usr/bin/pip3.8 pip
                ln -fs /usr/bin/pydoc3.8 pydoc
                ln -fs /usr/bin/python3.8 python
                ln -fs /usr/bin/python3.8-config python-config
            SHELL

            # Mounts
            # config.vm.synced_folder "../data", "/vagrant_data"
        end
    end
end
