#!/bin/bash
#
# Ansible initialization for CentOS server
# Platform: Unix
#
# Author: Dmitry Ivanov
#

echo "=== Welcome to Ansible raw init commands runner ==="
echo

# Environment
ANSIBLE_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REMOTE_USER=root
VAULT_PASS_FILE=${ANSIBLE_HOME}/ansible_password
VAULT_PASS_FILE_TMP=/tmp/ansible_password.tmp

# Temporary password files with autodeletion
trap "{ rm -f ${VAULT_PASS_FILE_TMP}; }" EXIT
cat ${VAULT_PASS_FILE} > ${VAULT_PASS_FILE_TMP}
chmod 600 ${VAULT_PASS_FILE_TMP}

# Script
ansible-playbook  -i ${ANSIBLE_HOME}/module1_inventory          \
                  -u ${REMOTE_USER} -k                          \
                  --vault-password-file=${VAULT_PASS_FILE_TMP}  \
                  ${ANSIBLE_HOME}/module1_init.yml              \
                  $@
echo
exit 0

